import path from 'node:path';

export const ENV_MODES = ['local', 'preview', 'production'];

export const APP_CONFIG = {
  studio: {
    id: 'studio',
    label: '@forge/studio',
    dir: path.join('apps', 'studio'),
    envExamplePath: path.join('apps', 'studio', '.env.example'),
    envLocalPath: path.join('apps', 'studio', '.env.local'),
    envDevelopmentPath: path.join('apps', 'studio', '.env.development.local'),
    envProductionPath: path.join('apps', 'studio', '.env.production.local'),
  },
  platform: {
    id: 'platform',
    label: '@forge/platform',
    dir: path.join('apps', 'platform'),
    envExamplePath: path.join('apps', 'platform', '.env.example'),
    envLocalPath: path.join('apps', 'platform', '.env.local'),
    envDevelopmentPath: path.join('apps', 'platform', '.env.development.local'),
    envProductionPath: path.join('apps', 'platform', '.env.production.local'),
  },
};

export const APP_ALIASES = {
  marketing: 'platform',
};

export const SECTION_META = {
  studio: {
    runtime: {
      title: 'Core runtime',
      description: 'Payload and app URL configuration for Studio runtime.',
    },
    localDev: {
      title: 'Local developer bootstrap',
      description: 'Local-only auth bootstrap and seed defaults.',
    },
    ai: {
      title: 'AI and model routing',
      description: 'OpenRouter and optional Copilot dev/public key settings.',
    },
    stripe: {
      title: 'Stripe and billing',
      description: 'Checkout, webhooks, and storage add-on billing variables.',
    },
    media: {
      title: 'Media upload and voice',
      description: 'S3-compatible upload and ElevenLabs voice integration.',
    },
    analytics: {
      title: 'Analytics and logging',
      description: 'PostHog analytics/flags and structured logging controls.',
    },
    communication: {
      title: 'Email and announcements',
      description: 'Optional newsletter/notification sender variables.',
    },
    cors: {
      title: 'Cross-origin platform auth',
      description: 'Allowed origins for Platform -> Studio credentialed requests.',
    },
  },
  platform: {
    runtime: {
      title: 'Core runtime',
      description: 'Platform -> Studio API boundary and local development defaults.',
    },
    analytics: {
      title: 'Analytics',
      description: 'Optional PostHog analytics values for platform pages.',
    },
    docs: {
      title: 'Docs and branding',
      description: 'Optional docs/github metadata used in docs layout shell.',
    },
  },
};

/**
 * @typedef {{
 * app: 'studio' | 'platform',
 * key: string,
 * section: string,
 * description: string,
 * exampleDefault?: string,
 * requiredIn?: Array<'local'|'preview'|'production'>,
 * secret?: boolean,
 * localOnly?: boolean,
 * dependsOn?: { key: string, equals?: string, notEquals?: string, truthy?: boolean },
 * launchGroup?: string,
 * vercelTargets?: Array<'production'|'preview'>,
 * sharedValueHint?: string
 * }} EnvEntry
 */

/** @type {EnvEntry[]} */
export const ENV_MANIFEST = [
  {
    app: 'studio',
    key: 'PAYLOAD_SECRET',
    section: 'runtime',
    description: 'Payload auth secret.',
    exampleDefault: 'dev-secret-change-me',
    requiredIn: ['local', 'preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'DATABASE_URI',
    section: 'runtime',
    description: 'Database connection URI. Optional in local (sqlite default), required in preview/production.',
    exampleDefault: 'file:./data/payload.db',
    requiredIn: ['preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_APP_URL',
    section: 'runtime',
    description: 'Public Studio URL used in redirects and checkout fallbacks.',
    exampleDefault: 'http://localhost:3000',
    requiredIn: ['preview', 'production'],
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_LOCAL_DEV_AUTO_ADMIN',
    section: 'localDev',
    description: 'Enable local-only auto-login bootstrap for seeded admin (set 0 to disable).',
    exampleDefault: '1',
    requiredIn: ['local'],
    localOnly: true,
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_LOCAL_DEV_AUTO_ADMIN_EMAIL',
    section: 'localDev',
    description: 'Local auto-admin email used by LocalDevAuthGate.',
    exampleDefault: 'admin@forge.local',
    requiredIn: ['local'],
    localOnly: true,
    dependsOn: { key: 'NEXT_PUBLIC_LOCAL_DEV_AUTO_ADMIN', notEquals: '0' },
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_LOCAL_DEV_AUTO_ADMIN_PASSWORD',
    section: 'localDev',
    description: 'Local auto-admin password used by LocalDevAuthGate.',
    exampleDefault: 'admin12345',
    requiredIn: ['local'],
    localOnly: true,
    secret: true,
    dependsOn: { key: 'NEXT_PUBLIC_LOCAL_DEV_AUTO_ADMIN', notEquals: '0' },
  },
  {
    app: 'studio',
    key: 'SEED_ADMIN_EMAIL',
    section: 'localDev',
    description: 'Optional admin seed override for local data bootstrap.',
    exampleDefault: 'admin@forge.local',
    localOnly: true,
  },
  {
    app: 'studio',
    key: 'SEED_ADMIN_PASSWORD',
    section: 'localDev',
    description: 'Optional admin seed password override.',
    exampleDefault: 'admin12345',
    localOnly: true,
    secret: true,
  },
  {
    app: 'studio',
    key: 'SEED_USER_EMAIL',
    section: 'localDev',
    description: 'Optional non-admin user seed override.',
    exampleDefault: 'user@forge.local',
    localOnly: true,
  },
  {
    app: 'studio',
    key: 'SEED_USER_PASSWORD',
    section: 'localDev',
    description: 'Optional non-admin user seed password override.',
    exampleDefault: 'user12345',
    localOnly: true,
    secret: true,
  },
  {
    app: 'studio',
    key: 'OPENROUTER_API_KEY',
    section: 'ai',
    description: 'OpenRouter API key for chat, planning, structured output, and image routes.',
    requiredIn: ['preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'OPENROUTER_BASE_URL',
    section: 'ai',
    description: 'Optional OpenRouter base URL override.',
    exampleDefault: 'https://openrouter.ai/api/v1',
  },
  {
    app: 'studio',
    key: 'OPENROUTER_TIMEOUT_MS',
    section: 'ai',
    description: 'Optional OpenRouter timeout in milliseconds.',
    exampleDefault: '60000',
  },
  {
    app: 'studio',
    key: 'AI_LANGGRAPH_ENABLED',
    section: 'ai',
    description: 'Enable LangGraph orchestration path in /api/assistant-chat (1 enabled).',
    exampleDefault: '0',
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_AI_LANGGRAPH_ENABLED',
    section: 'ai',
    description: 'Client mirror flag for LangGraph transport metadata wiring (1 enabled).',
    exampleDefault: '0',
  },
  {
    app: 'studio',
    key: 'OPENROUTER_RESPONSES_PROBE',
    section: 'ai',
    description: 'Enable/disable responses compatibility probing (1 enabled, 0 disabled).',
    exampleDefault: '1',
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_COPILOTKIT_API_KEY',
    section: 'ai',
    description: 'Optional CopilotKit public key for dev tooling.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'STRIPE_SECRET_KEY',
    section: 'stripe',
    description: 'Stripe secret API key.',
    requiredIn: ['preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'STRIPE_WEBHOOK_SECRET',
    section: 'stripe',
    description: 'Stripe webhook signing secret.',
    requiredIn: ['preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'STRIPE_PRICE_ID_PRO',
    section: 'stripe',
    description: 'Stripe price id for Pro subscription checkout.',
    requiredIn: ['preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'STRIPE_PRICE_ID_STORAGE_ADDON',
    section: 'stripe',
    description: 'Stripe price id for storage add-on checkout.',
    requiredIn: ['preview', 'production'],
    secret: true,
  },
  {
    app: 'studio',
    key: 'STORAGE_ADDON_BYTES',
    section: 'stripe',
    description: 'Storage bytes granted per storage add-on checkout.',
    exampleDefault: '53687091200',
  },
  {
    app: 'studio',
    key: 'STRIPE_ACCOUNT_ID',
    section: 'stripe',
    description: 'Optional Stripe account id reference used in docs/ops.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'STRIPE_SUPPORT_EMAIL',
    section: 'stripe',
    description: 'Optional support contact for Stripe product metadata.',
    exampleDefault: 'you@example.com',
  },
  {
    app: 'studio',
    key: 'STRIPE_SUPPORT_URL',
    section: 'stripe',
    description: 'Optional support URL for Stripe product metadata.',
    exampleDefault: 'https://example.com/support',
  },
  {
    app: 'studio',
    key: 'PRIVACY_POLICY_URL',
    section: 'stripe',
    description: 'Optional privacy URL for Stripe/legal metadata.',
    exampleDefault: 'https://example.com/privacy-policy',
  },
  {
    app: 'studio',
    key: 'TERMS_OF_SERVICE_URL',
    section: 'stripe',
    description: 'Optional terms URL for Stripe/legal metadata.',
    exampleDefault: 'https://example.com/terms-of-service',
  },
  {
    app: 'studio',
    key: 'BETTER_UPLOAD_BUCKET',
    section: 'media',
    description: 'S3-compatible bucket name for Better Upload.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'AWS_ACCESS_KEY_ID',
    section: 'media',
    description: 'S3-compatible access key id.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'AWS_SECRET_ACCESS_KEY',
    section: 'media',
    description: 'S3-compatible secret access key.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'AWS_REGION',
    section: 'media',
    description: 'S3-compatible region.',
    exampleDefault: 'us-east-1',
  },
  {
    app: 'studio',
    key: 'AWS_S3_BUCKET',
    section: 'media',
    description: 'Optional legacy S3 bucket fallback key.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'ELEVENLABS_API_KEY',
    section: 'media',
    description: 'ElevenLabs API key for voice endpoints.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_POSTHOG_KEY',
    section: 'analytics',
    description: 'Optional PostHog project key.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_POSTHOG_HOST',
    section: 'analytics',
    description: 'PostHog host URL.',
    exampleDefault: 'https://us.i.posthog.com',
  },
  {
    app: 'studio',
    key: 'LOG_LEVEL',
    section: 'analytics',
    description: 'Logger level (debug, info, warn, error).',
    exampleDefault: 'info',
  },
  {
    app: 'studio',
    key: 'LOG_FILE',
    section: 'analytics',
    description: 'Optional log file path for Studio server logs.',
    exampleDefault: '.logs/studio.log',
  },
  {
    app: 'studio',
    key: 'LOG_NAMESPACES',
    section: 'analytics',
    description: 'Optional comma-separated namespace filter for logging.',
  },
  {
    app: 'studio',
    key: 'ALLOW_CLIENT_LOG',
    section: 'analytics',
    description: 'Allow browser log relay endpoint in development (1 enabled).',
    exampleDefault: '0',
    localOnly: true,
  },
  {
    app: 'studio',
    key: 'NEXT_PUBLIC_LOG_TO_SERVER',
    section: 'analytics',
    description: 'Enable browser log forwarding to /api/dev/log (1 enabled).',
    exampleDefault: '0',
    localOnly: true,
  },
  {
    app: 'studio',
    key: 'RESEND_API_KEY',
    section: 'communication',
    description: 'Optional Resend API key for newsletter welcome mail.',
    secret: true,
  },
  {
    app: 'studio',
    key: 'FROM_EMAIL',
    section: 'communication',
    description: 'Sender email used by newsletter route when Resend is enabled.',
    exampleDefault: 'Forge <onboarding@resend.dev>',
  },
  {
    app: 'studio',
    key: 'CORS_ALLOWED_ORIGINS',
    section: 'cors',
    description: 'Comma-separated allowlist for credentialed cross-origin API access.',
    exampleDefault: 'http://localhost:3001',
  },
  {
    app: 'studio',
    key: 'PLATFORM_APP_URL',
    section: 'cors',
    description: 'Optional single-origin alias for platform app URL.',
    exampleDefault: 'http://localhost:3001',
  },
  {
    app: 'platform',
    key: 'NEXT_PUBLIC_STUDIO_APP_URL',
    section: 'runtime',
    description: 'Studio API/app URL for platform auth, data, and Open Studio links.',
    exampleDefault: 'http://localhost:3000',
    requiredIn: ['local', 'preview', 'production'],
  },
  {
    app: 'platform',
    key: 'NEXT_PUBLIC_POSTHOG_KEY',
    section: 'analytics',
    description: 'Optional PostHog project key for platform analytics.',
    secret: true,
  },
  {
    app: 'platform',
    key: 'NEXT_PUBLIC_POSTHOG_HOST',
    section: 'analytics',
    description: 'PostHog host URL.',
    exampleDefault: 'https://us.i.posthog.com',
  },
  {
    app: 'platform',
    key: 'NEXT_PUBLIC_GITHUB_URL',
    section: 'docs',
    description: 'Optional GitHub link shown in docs/layout shell.',
    exampleDefault: 'https://github.com',
  },
];
