/** Generated by scripts/build-showcase-registry.mjs - do not edit */

'use client';

import * as React from 'react';

export const SHOWCASE_REGISTRY: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
  'accordion-demo': React.lazy(() => import('../registry/atoms/accordion-demo/AccordionDemo').then((m: any) => ({ default: m.AccordionDemo ?? m.default }))),
  'badge-demo': React.lazy(() => import('../registry/atoms/badge-demo/BadgeDemo').then((m: any) => ({ default: m.BadgeDemo ?? m.default }))),
  'button-demo': React.lazy(() => import('../registry/atoms/button-demo/ButtonDemo').then((m: any) => ({ default: m.ButtonDemo ?? m.default }))),
  'card-demo': React.lazy(() => import('../registry/atoms/card-demo/CardDemo').then((m: any) => ({ default: m.CardDemo ?? m.default }))),
  'density-demo': React.lazy(() => import('../registry/atoms/density-demo/DensityDemo').then((m: any) => ({ default: m.DensityDemo ?? m.default }))),
  'dialog-demo': React.lazy(() => import('../registry/atoms/dialog-demo/DialogDemo').then((m: any) => ({ default: m.DialogDemo ?? m.default }))),
  'dropdown-menu-demo': React.lazy(() => import('../registry/atoms/dropdown-menu-demo/DropdownMenuDemo').then((m: any) => ({ default: m.DropdownMenuDemo ?? m.default }))),
  'input-demo': React.lazy(() => import('../registry/atoms/input-demo/InputDemo').then((m: any) => ({ default: m.InputDemo ?? m.default }))),
  'label-demo': React.lazy(() => import('../registry/atoms/label-demo/LabelDemo').then((m: any) => ({ default: m.LabelDemo ?? m.default }))),
  'select-demo': React.lazy(() => import('../registry/atoms/select-demo/SelectDemo').then((m: any) => ({ default: m.SelectDemo ?? m.default }))),
  'switch-demo': React.lazy(() => import('../registry/atoms/switch-demo/SwitchDemo').then((m: any) => ({ default: m.SwitchDemo ?? m.default }))),
  'tabs-demo': React.lazy(() => import('../registry/atoms/tabs-demo/TabsDemo').then((m: any) => ({ default: m.TabsDemo ?? m.default }))),
  'theme-switcher-demo': React.lazy(() => import('../registry/atoms/theme-switcher-demo/ThemeSwitcherDemo').then((m: any) => ({ default: m.ThemeSwitcherDemo ?? m.default }))),
  'assistant-panel-demo': React.lazy(() => import('../registry/molecules/assistant-panel-demo/AssistantPanelDemo').then((m: any) => ({ default: m.AssistantPanelDemo ?? m.default }))),
  'attachment-demo': React.lazy(() => import('../registry/molecules/attachment-demo/AttachmentDemo').then((m: any) => ({ default: m.AttachmentDemo ?? m.default }))),
  'dock-layout-demo': React.lazy(() => import('../registry/molecules/dock-layout-demo/DockLayoutDemo').then((m: any) => ({ default: m.DockLayoutDemo ?? m.default }))),
  'dock-panel-demo': React.lazy(() => import('../registry/molecules/dock-panel-demo/DockPanelDemo').then((m: any) => ({ default: m.DockPanelDemo ?? m.default }))),
  'dock-sidebar-demo': React.lazy(() => import('../registry/molecules/dock-sidebar-demo/DockSidebarDemo').then((m: any) => ({ default: m.DockSidebarDemo ?? m.default }))),
  'panel-tabs-demo': React.lazy(() => import('../registry/molecules/panel-tabs-demo/PanelTabsDemo').then((m: any) => ({ default: m.PanelTabsDemo ?? m.default }))),
  'plan-card-demo': React.lazy(() => import('../registry/molecules/plan-card-demo/PlanCardDemo').then((m: any) => ({ default: m.PlanCardDemo ?? m.default }))),
  'plan-demo': React.lazy(() => import('../registry/molecules/plan-demo/PlanDemo').then((m: any) => ({ default: m.PlanDemo ?? m.default }))),
  'settings-panel-demo': React.lazy(() => import('../registry/molecules/settings-panel-demo/SettingsPanelDemo').then((m: any) => ({ default: m.SettingsPanelDemo ?? m.default }))),
  'settings-system-demo': React.lazy(() => import('../registry/molecules/settings-system-demo/SettingsSystemDemo').then((m: any) => ({ default: m.SettingsSystemDemo ?? m.default }))),
  'studio-menubar-contribution-demo': React.lazy(() => import('../registry/molecules/studio-menubar-contribution-demo/StudioMenubarContributionDemo').then((m: any) => ({ default: m.StudioMenubarContributionDemo ?? m.default }))),
  'toolbar-workspace-settings-menu-demo': React.lazy(() => import('../registry/molecules/toolbar-workspace-settings-menu-demo/ToolbarWorkspaceSettingsMenuDemo').then((m: any) => ({ default: m.ToolbarWorkspaceSettingsMenuDemo ?? m.default }))),
  'workspace-inspector-demo': React.lazy(() => import('../registry/molecules/workspace-inspector-demo/WorkspaceInspectorDemo').then((m: any) => ({ default: m.WorkspaceInspectorDemo ?? m.default }))),
  'workspace-overlay-demo': React.lazy(() => import('../registry/molecules/workspace-overlay-demo/WorkspaceOverlayDemo').then((m: any) => ({ default: m.WorkspaceOverlayDemo ?? m.default }))),
  'workspace-shell-demo': React.lazy(() => import('../registry/molecules/workspace-shell-demo/WorkspaceShellDemo').then((m: any) => ({ default: m.WorkspaceShellDemo ?? m.default }))),
  'workspace-toolbar-demo': React.lazy(() => import('../registry/molecules/workspace-toolbar-demo/WorkspaceToolbarDemo').then((m: any) => ({ default: m.WorkspaceToolbarDemo ?? m.default }))),
  'codebase-agent-strategy-editor': React.lazy(() => import('../registry/organisms/codebase-agent-strategy-editor/index').then((m: any) => ({ default: m.default ?? m.default }))),
  'studio-workbench-demo': React.lazy(() => import('../registry/organisms/studio-workbench-demo/StudioWorkbenchDemo').then((m: any) => ({ default: m.StudioWorkbenchDemo ?? m.default })))
};
