/* eslint-disable */
// Generated by scripts/generate-platform-component-docs.mjs
// Do not edit manually.

export const COMPONENT_DEMO_IDS = [] as const;

type _TupleEl = (typeof COMPONENT_DEMO_IDS)[number];
export type ComponentDemoId = [_TupleEl] extends [never] ? string : _TupleEl;
