/**
 * Do not edit. Generated by @forge/forge-codegen.
 * Source: workspace components (WORKSPACE_ID, WORKSPACE_LABEL, WorkspaceLayout.Panel).
 * Single import surface for this studio app.
 */

import type { WorkspacePanelSpec, WorkspaceLayoutDefinition } from '@forge/shared';

/** App identity (for spec consistency; use on root when desired). */
export const APP_ID = "repo-studio";
export const APP_LABEL = "Repo Studio";

export const WORKSPACE_IDS = ["planning","extensions","database","git","code"] as const;
export type WorkspaceId = (typeof WORKSPACE_IDS)[number];

export const WORKSPACE_LABELS: Record<WorkspaceId, string> = {
  "planning": "Planning",
  "extensions": "Extensions",
  "database": "Database",
  "git": "Git",
  "code": "Code"
};

/** Panel ids that must never be hidden (e.g. viewport-as-canvas). */
export const PINNED_PANEL_IDS: readonly string[] = ["viewport"];

const LAYOUT_DEFINITIONS: Record<WorkspaceId, WorkspaceLayoutDefinition> = {
  "planning": {
    "workspaceId": "planning",
    "label": "Planning",
    "layoutId": "repo-planning",
    "mainAnchorPanelId": "viewport",
    "mainPanelIds": [
      "viewport"
    ],
    "panelSpecs": [
      {
        "id": "planning-prd",
        "rail": "left",
        "label": "PRD",
        "key": "panel.visible.repo-planning-prd"
      },
      {
        "id": "planning-status",
        "rail": "left",
        "label": "Status",
        "key": "panel.visible.repo-planning-status"
      },
      {
        "id": "planning-decisions",
        "rail": "left",
        "label": "Decisions",
        "key": "panel.visible.repo-planning-decisions"
      },
      {
        "id": "planning-regression",
        "rail": "left",
        "label": "Regression",
        "key": "panel.visible.repo-planning-regression"
      },
      {
        "id": "planning-phases",
        "rail": "left",
        "label": "Phases",
        "key": "panel.visible.repo-planning-phases"
      },
      {
        "id": "planning-tasks",
        "rail": "left",
        "label": "Tasks",
        "key": "panel.visible.repo-planning-tasks"
      },
      {
        "id": "planning-documents",
        "rail": "left",
        "label": "Documents",
        "key": "panel.visible.repo-planning-documents"
      },
      {
        "id": "viewport",
        "rail": "main",
        "label": "Viewport",
        "key": "panel.visible.repo-viewport"
      },
      {
        "id": "assistant",
        "rail": "right",
        "label": "Assistant",
        "key": "panel.visible.repo-assistant"
      }
    ]
  },
  "extensions": {
    "workspaceId": "extensions",
    "label": "Extensions",
    "layoutId": "repo-extensions",
    "mainAnchorPanelId": "extensions-registry",
    "mainPanelIds": [
      "extensions-registry"
    ],
    "panelSpecs": [
      {
        "id": "extensions-installed",
        "rail": "left",
        "label": "Installed",
        "key": "panel.visible.repo-extensions-installed"
      },
      {
        "id": "extensions-registry",
        "rail": "main",
        "label": "Registry",
        "key": "panel.visible.repo-extensions-registry"
      },
      {
        "id": "assistant",
        "rail": "right",
        "label": "Assistant",
        "key": "panel.visible.repo-assistant"
      }
    ]
  },
  "database": {
    "workspaceId": "database",
    "label": "Database",
    "layoutId": "repo-database",
    "mainAnchorPanelId": "database",
    "mainPanelIds": [
      "database"
    ],
    "panelSpecs": [
      {
        "id": "database",
        "rail": "main",
        "label": "Database",
        "key": "panel.visible.repo-database"
      },
      {
        "id": "assistant",
        "rail": "right",
        "label": "Assistant",
        "key": "panel.visible.repo-assistant"
      }
    ]
  },
  "git": {
    "workspaceId": "git",
    "label": "Git",
    "layoutId": "repo-git",
    "mainAnchorPanelId": "code",
    "mainPanelIds": [
      "code",
      "git"
    ],
    "panelSpecs": [
      {
        "id": "code",
        "rail": "main",
        "label": "Code",
        "key": "panel.visible.repo-code"
      },
      {
        "id": "git",
        "rail": "main",
        "label": "Git",
        "key": "panel.visible.repo-git"
      },
      {
        "id": "diff",
        "rail": "bottom",
        "label": "Diff",
        "key": "panel.visible.repo-diff"
      },
      {
        "id": "assistant",
        "rail": "right",
        "label": "Assistant",
        "key": "panel.visible.repo-assistant"
      }
    ]
  },
  "code": {
    "workspaceId": "code",
    "label": "Code",
    "layoutId": "repo-code",
    "mainAnchorPanelId": "viewport",
    "mainPanelIds": [
      "viewport"
    ],
    "panelSpecs": [
      {
        "id": "viewport",
        "rail": "main",
        "label": "Viewport",
        "key": "panel.visible.repo-viewport"
      },
      {
        "id": "assistant",
        "rail": "right",
        "label": "Assistant",
        "key": "panel.visible.repo-assistant"
      },
      {
        "id": "diff",
        "rail": "bottom",
        "label": "Diff",
        "key": "panel.visible.repo-diff"
      },
      {
        "id": "git",
        "rail": "bottom",
        "label": "Git",
        "key": "panel.visible.repo-git"
      }
    ]
  }
};

const EXTENSION_LAYOUT_DEFINITIONS: Record<string, WorkspaceLayoutDefinition> = {};

const FALLBACK_WORKSPACE_ID: WorkspaceId = "planning";

function getDefinitionSafe(workspaceId: string): WorkspaceLayoutDefinition {
  if (workspaceId in LAYOUT_DEFINITIONS) {
    return LAYOUT_DEFINITIONS[workspaceId as WorkspaceId];
  }
  if (process.env.NODE_ENV !== 'production') {
    console.warn(
      '[App spec] Unknown workspace id "%s", falling back to %s.',
      workspaceId,
      FALLBACK_WORKSPACE_ID,
    );
  }
  return LAYOUT_DEFINITIONS[FALLBACK_WORKSPACE_ID];
}

export function getWorkspaceLayoutDefinition(workspaceId: WorkspaceId): WorkspaceLayoutDefinition {
  return LAYOUT_DEFINITIONS[workspaceId];
}

export function getExtensionWorkspaceLayoutDefinition(workspaceId: string): WorkspaceLayoutDefinition | undefined {
  return EXTENSION_LAYOUT_DEFINITIONS[String(workspaceId || '').trim()];
}

export function getWorkspaceLayoutId(workspaceId: string): string {
  return getDefinitionSafe(workspaceId).layoutId;
}

export function getWorkspacePanelSpecs(workspaceId: string): WorkspacePanelSpec[] {
  return getDefinitionSafe(workspaceId).panelSpecs;
}

function normalizePanelIds(panelIds: unknown[]) {
  return [...new Set(
    (panelIds || [])
      .map((panelId) => String(panelId || '').trim())
      .filter(Boolean),
  )];
}

export function sanitizeWorkspaceHiddenPanelIds(workspaceId: WorkspaceId, panelIds: unknown[]): string[] {
  const definition = getWorkspaceLayoutDefinition(workspaceId);
  const allowedIds = new Set(definition.panelSpecs.map((p) => p.id));
  const pinnedSet = new Set(PINNED_PANEL_IDS);
  const hidden = normalizePanelIds(panelIds)
    .filter((id) => allowedIds.has(id))
    .filter((id) => !pinnedSet.has(id));
  const hiddenSet = new Set(hidden);
  const visibleMainPanels = definition.mainPanelIds.filter((id) => !hiddenSet.has(id));
  if (visibleMainPanels.length === 0) {
    hiddenSet.delete(definition.mainAnchorPanelId);
    const fallbackVisible = definition.mainPanelIds.filter((id) => !hiddenSet.has(id));
    if (fallbackVisible.length === 0 && definition.mainPanelIds[0]) {
      hiddenSet.delete(definition.mainPanelIds[0]);
    }
  }
  return [...hiddenSet].sort((a, b) => a.localeCompare(b));
}

export function createEmptyWorkspaceHiddenPanelMap(): Partial<Record<WorkspaceId, string[]>> {
  return WORKSPACE_IDS.reduce((acc, workspaceId) => {
    acc[workspaceId] = [];
    return acc;
  }, {} as Partial<Record<WorkspaceId, string[]>>);
}

/** Merged settings defaults for this app. */
export const REPO_SETTINGS_GENERATED_DEFAULTS = {
  "commands": {
    "view": {
      "query": "",
      "source": "all",
      "status": "all",
      "tab": "recommended",
      "sort": "id"
    },
    "disabledCommandIds": [],
    "confirmRuns": true
  },
  "panels": {
    "hiddenPanelIds": []
  },
  "loops": {
    "activeLoopId": "default"
  },
  "assistant": {
    "prompts": {
      "byLoop": {
        "default": {
          "forgeAssistant": "",
          "codexAssistant": ""
        }
      },
      "forgeAssistant": "",
      "codexAssistant": ""
    }
  },
  "env": {
    "profile": "forge-agent",
    "mode": "local"
  },
  "platform": {
    "baseUrl": "",
    "autoValidate": true,
    "lastStatus": "disconnected",
    "lastValidatedAt": ""
  },
  "reviewQueue": {
    "trustMode": "require-approval",
    "autoApplyEnabled": false,
    "lastAutoApplyAt": ""
  }
} as const;
