/* eslint-disable */
// Generated by scripts/generate-platform-component-docs.mjs
// Do not edit manually.

export const COMPONENT_DEMO_IDS = [
  'editor.dock-layout',
  'editor.dock-panel',
  'editor.dock-sidebar',
  'editor.dockview-slot-tab',
  'editor.editor-bottom-panel',
  'editor.editor-button',
  'editor.editor-header',
  'editor.editor-inspector',
  'editor.editor-overlay-surface',
  'editor.editor-panel',
  'editor.editor-rail',
  'editor.editor-review-bar',
  'editor.editor-settings-trigger',
  'editor.editor-shell',
  'editor.editor-sidebar',
  'editor.editor-status-bar',
  'editor.editor-tab',
  'editor.editor-tab-group',
  'editor.editor-toolbar',
  'editor.editor-tooltip',
  'editor.panel-registration-context',
  'editor.panel-settings',
  'editor.panel-tabs',
  'editor.settings-tabs',
  'editor.settings-trigger-context',
  'editor.toolbar-editor-edit-menu',
  'editor.toolbar-editor-file-menu',
  'editor.toolbar-editor-help-menu',
  'editor.toolbar-editor-menubar',
  'editor.toolbar-editor-project-select',
  'editor.toolbar-editor-settings-menu',
  'editor.toolbar-editor-view-menu',
  'editor.viewport-meta',
] as const;

export type ComponentDemoId = (typeof COMPONENT_DEMO_IDS)[number];
