/**
 * Settings codegen: mount the settings registration tree, read the registry,
 * and write generated/defaults.ts (APP_DEFAULTS, VIEWPORT_DEFAULTS, getViewportDefaults).
 * Run via: SETTINGS_CODEGEN=1 pnpm test -- settings-codegen (or pnpm settings:generate).
 * Uses Node env (SETTINGS_CODEGEN=1) + react-test-renderer to avoid jsdom/canvas.
 */

import * as React from 'react';
import TestRenderer from 'react-test-renderer';
import * as fs from 'fs';
import * as path from 'path';
import { AppSettingsProvider } from '@/components/settings/AppSettingsProvider';
import { AppSettingsRegistrations } from '@/components/settings/AppSettingsRegistrations';
import { ViewportSettingsProvider } from '@/components/settings/ViewportSettingsProvider';
import { GraphViewportSettings } from '@/components/settings/GraphViewportSettings';
import { useSettingsRegistryStore } from '@/lib/editor-registry/settings-registry';
import type { SettingsSection } from '@/components/settings/types';

const VIEWPORT_KEYS = ['dialogue:narrative', 'dialogue:storylet', 'character:main'] as const;

function scopeKey(scope: string, scopeId: string | null): string {
  return `${scope}:${scopeId ?? ''}`;
}

function sectionsToDefaults(sections: SettingsSection[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const section of sections) {
    for (const field of section.fields) {
      if (field.default !== undefined) {
        out[field.key] = field.default;
      }
    }
  }
  return out;
}

function generateDefaultsTs(appDefaults: Record<string, unknown>, viewportDefaults: Record<string, Record<string, unknown>>): string {
  const header = `/**
 * Generated by settings-codegen.test.tsx. Do not edit by hand.
 * Run: pnpm settings:generate (or pnpm test -- settings-codegen)
 */`;

  const appStr = JSON.stringify(appDefaults, null, 2);
  const viewportStr = JSON.stringify(viewportDefaults, null, 2);

  return `${header}

export type SettingsDefaults = Record<string, unknown>;

export const APP_DEFAULTS: SettingsDefaults = ${appStr};

export const VIEWPORT_DEFAULTS: Record<string, SettingsDefaults> = ${viewportStr};

export function getViewportDefaults(editorId: string, viewportId: string): SettingsDefaults {
  const key = \`\${editorId}:\${viewportId}\`;
  return VIEWPORT_DEFAULTS[key] ?? {};
}
`;
}

describe('Settings codegen', () => {
  it('mounts tree, reads registry, and writes generated/defaults.ts', () => {
    const store = useSettingsRegistryStore.getState();
    // Reset so we only see what we register in this run
    const initialSections = { ...store.sections };

    function Tree() {
      return (
        <>
          <AppSettingsProvider>
            <AppSettingsRegistrations />
          </AppSettingsProvider>
          {VIEWPORT_KEYS.map((key) => {
            const [editorId, viewportId] = key.split(':');
            return (
              <ViewportSettingsProvider key={key} editorId={editorId} viewportId={viewportId}>
                <GraphViewportSettings />
              </ViewportSettingsProvider>
            );
          })}
        </>
      );
    }

    TestRenderer.act(() => {
      TestRenderer.create(<Tree />);
    });

    const sections = useSettingsRegistryStore.getState().sections;

    const appKey = scopeKey('app', null);
    const appSections = sections[appKey] ?? [];
    const appDefaults = sectionsToDefaults(appSections);

    const viewportDefaults: Record<string, Record<string, unknown>> = {};
    for (const key of VIEWPORT_KEYS) {
      const scopeKeyStr = scopeKey('viewport', key);
      const scopeSections = sections[scopeKeyStr] ?? [];
      viewportDefaults[key] = sectionsToDefaults(scopeSections);
    }

    expect(Object.keys(appDefaults).length).toBeGreaterThan(0);
    expect(appDefaults['ai.agentName']).toBe('Forge Assistant');

    const outDir = path.join(process.cwd(), 'lib', 'settings', 'generated');
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }
    const outPath = path.join(outDir, 'defaults.ts');
    const content = generateDefaultsTs(appDefaults, viewportDefaults);
    fs.writeFileSync(outPath, content, 'utf-8');

    // Restore so other tests don't see our sections
    useSettingsRegistryStore.setState({ sections: initialSections });
  });
});
