/**
 * Do not edit. Generated by @forge/forge-codegen.
 * Source: workspace components (WORKSPACE_ID, WORKSPACE_LABEL, WorkspaceLayout.Panel).
 * Single import surface for this studio app.
 */

import type { WorkspacePanelSpec, WorkspaceLayoutDefinition } from '@forge/shared';

export const WORKSPACE_IDS = ["dialogue","character","strategy"] as const;
export type WorkspaceId = (typeof WORKSPACE_IDS)[number];

export const WORKSPACE_LABELS: Record<WorkspaceId, string> = {
  "dialogue": "Dialogue",
  "character": "Characters",
  "strategy": "Strategy"
};

/** Panel ids that must never be hidden (e.g. viewport-as-canvas). */
export const PINNED_PANEL_IDS: readonly string[] = [];

const LAYOUT_DEFINITIONS: Record<WorkspaceId, WorkspaceLayoutDefinition> = {
  "dialogue": {
    "workspaceId": "dialogue",
    "label": "Dialogue",
    "layoutId": "studio-dialogue",
    "mainAnchorPanelId": "main",
    "mainPanelIds": [
      "main",
      "bottom"
    ],
    "panelSpecs": [
      {
        "id": "left",
        "rail": "left",
        "label": "Library",
        "key": "panel.visible.dialogue-left"
      },
      {
        "id": "main",
        "rail": "main",
        "label": "Dialogue Graphs",
        "key": "panel.visible.dialogue-main"
      },
      {
        "id": "right",
        "rail": "right",
        "label": "Inspector",
        "key": "panel.visible.dialogue-right"
      },
      {
        "id": "yarn",
        "rail": "right",
        "label": "Yarn",
        "key": "panel.visible.dialogue-yarn"
      },
      {
        "id": "chat",
        "rail": "right",
        "label": "Chat",
        "key": "panel.visible.dialogue-chat"
      },
      {
        "id": "bottom",
        "label": "Bottom panel",
        "key": "panel.visible.dialogue-bottom",
        "rail": "main"
      }
    ]
  },
  "character": {
    "workspaceId": "character",
    "label": "Characters",
    "layoutId": "studio-character",
    "mainAnchorPanelId": "main",
    "mainPanelIds": [
      "main"
    ],
    "panelSpecs": [
      {
        "id": "left",
        "rail": "left",
        "label": "Characters",
        "key": "panel.visible.character-left"
      },
      {
        "id": "main",
        "rail": "main",
        "label": "Graph",
        "key": "panel.visible.character-main"
      },
      {
        "id": "right",
        "rail": "right",
        "label": "Properties",
        "key": "panel.visible.character-right"
      },
      {
        "id": "chat",
        "rail": "right",
        "label": "Chat",
        "key": "panel.visible.character-chat"
      }
    ]
  },
  "strategy": {
    "workspaceId": "strategy",
    "label": "Strategy",
    "layoutId": "studio-strategy",
    "mainAnchorPanelId": "",
    "mainPanelIds": [],
    "panelSpecs": []
  }
};

const FALLBACK_WORKSPACE_ID: WorkspaceId = "dialogue";

function getDefinitionSafe(workspaceId: string): WorkspaceLayoutDefinition {
  if (workspaceId in LAYOUT_DEFINITIONS) {
    return LAYOUT_DEFINITIONS[workspaceId as WorkspaceId];
  }
  if (process.env.NODE_ENV !== 'production') {
    console.warn(
      '[App spec] Unknown workspace id "%s", falling back to %s.',
      workspaceId,
      FALLBACK_WORKSPACE_ID,
    );
  }
  return LAYOUT_DEFINITIONS[FALLBACK_WORKSPACE_ID];
}

export function getWorkspaceLayoutDefinition(workspaceId: WorkspaceId): WorkspaceLayoutDefinition {
  return LAYOUT_DEFINITIONS[workspaceId];
}

export function getWorkspaceLayoutId(workspaceId: string): string {
  return getDefinitionSafe(workspaceId).layoutId;
}

export function getWorkspacePanelSpecs(workspaceId: string): WorkspacePanelSpec[] {
  return getDefinitionSafe(workspaceId).panelSpecs;
}

function normalizePanelIds(panelIds: unknown[]) {
  return [...new Set(
    (panelIds || [])
      .map((panelId) => String(panelId || '').trim())
      .filter(Boolean),
  )];
}

export function sanitizeWorkspaceHiddenPanelIds(workspaceId: WorkspaceId, panelIds: unknown[]): string[] {
  const definition = getWorkspaceLayoutDefinition(workspaceId);
  const allowedIds = new Set(definition.panelSpecs.map((p) => p.id));
  const pinnedSet = new Set(PINNED_PANEL_IDS);
  const hidden = normalizePanelIds(panelIds)
    .filter((id) => allowedIds.has(id))
    .filter((id) => !pinnedSet.has(id));
  const hiddenSet = new Set(hidden);
  const visibleMainPanels = definition.mainPanelIds.filter((id) => !hiddenSet.has(id));
  if (visibleMainPanels.length === 0) {
    hiddenSet.delete(definition.mainAnchorPanelId);
    const fallbackVisible = definition.mainPanelIds.filter((id) => !hiddenSet.has(id));
    if (fallbackVisible.length === 0 && definition.mainPanelIds[0]) {
      hiddenSet.delete(definition.mainPanelIds[0]);
    }
  }
  return [...hiddenSet].sort((a, b) => a.localeCompare(b));
}

export function createEmptyWorkspaceHiddenPanelMap(): Partial<Record<WorkspaceId, string[]>> {
  return WORKSPACE_IDS.reduce((acc, workspaceId) => {
    acc[workspaceId] = [];
    return acc;
  }, {} as Partial<Record<WorkspaceId, string[]>>);
}

/** Merged settings defaults for this app. */
export const APP_SETTINGS_DEFAULTS = {} as const;
