/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface ForgeGraph {
  id: number;
  title: string;
  flow: unknown;
  createdAt?: string;
  updatedAt?: string;
}

export interface VideoDoc {
  id: number;
  title: string;
  graphId?: string | null;
  doc: unknown;
  createdAt?: string;
  updatedAt?: string;
}

export interface SettingsSnapshot {
  id: number;
  scope: 'app' | 'workspace' | 'editor';
  scopeId?: string | null;
  settings: unknown;
  label?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface AgentSession {
  id: number;
  domain: 'forge' | 'video';
  docId?: string | null;
  summary?: string | null;
  events?: unknown;
  createdAt?: string;
  updatedAt?: string;
}

export interface Config {
  collections: {
    'forge-graphs': ForgeGraph;
    'video-docs': VideoDoc;
    'settings-snapshots': SettingsSnapshot;
    'agent-sessions': AgentSession;
  };
  globals: {};
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
