import type { CollectionConfig } from 'payload';

export const AiUsageEvents: CollectionConfig = {
  slug: 'ai-usage-events',
  access: {
    read: ({ req }) => !!req.user,
    create: () => false,
    update: () => false,
    delete: () => false,
  },
  admin: {
    useAsTitle: 'requestId',
    description: 'Billing-grade AI usage ledger generated by server-side AI routes.',
  },
  fields: [
    {
      name: 'requestId',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      required: true,
    },
    {
      name: 'organization',
      type: 'relationship',
      relationTo: 'organizations',
    },
    {
      name: 'apiKey',
      type: 'relationship',
      relationTo: 'api-keys',
    },
    {
      name: 'authType',
      type: 'select',
      required: true,
      defaultValue: 'session',
      options: [
        { label: 'Session', value: 'session' },
        { label: 'API key', value: 'api_key' },
      ],
    },
    {
      name: 'provider',
      type: 'text',
      required: true,
    },
    {
      name: 'model',
      type: 'text',
      required: true,
    },
    {
      name: 'routeKey',
      type: 'text',
      required: true,
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'success',
      options: [
        { label: 'Success', value: 'success' },
        { label: 'Partial', value: 'partial' },
        { label: 'Error', value: 'error' },
      ],
    },
    {
      name: 'errorMessage',
      type: 'textarea',
    },
    {
      name: 'inputTokens',
      type: 'number',
      required: true,
      defaultValue: 0,
    },
    {
      name: 'outputTokens',
      type: 'number',
      required: true,
      defaultValue: 0,
    },
    {
      name: 'totalTokens',
      type: 'number',
      required: true,
      defaultValue: 0,
    },
    {
      name: 'inputCostUsd',
      type: 'number',
      required: true,
      defaultValue: 0,
    },
    {
      name: 'outputCostUsd',
      type: 'number',
      required: true,
      defaultValue: 0,
    },
    {
      name: 'totalCostUsd',
      type: 'number',
      required: true,
      defaultValue: 0,
    },
    {
      name: 'createdAt',
      type: 'date',
      required: true,
      defaultValue: () => new Date().toISOString(),
    },
  ],
};
