// @ts-nocheck
import * as __fd_glob_52 from "../../../docs/agent-artifacts/core/tool-usage.md?collection=docs"
import * as __fd_glob_51 from "../../../docs/agent-artifacts/core/STATUS.md?collection=docs"
import * as __fd_glob_50 from "../../../docs/agent-artifacts/core/errors-and-attempts.md?collection=docs"
import * as __fd_glob_49 from "../../../docs/agent-artifacts/core/decisions.md?collection=docs"
import * as __fd_glob_48 from "../../../docs/agent-artifacts/core/debugging-zustand-devtools.md?collection=docs"
import * as __fd_glob_47 from "../../../docs/agent-artifacts/core/compacting-and-archiving.md?collection=docs"
import * as __fd_glob_46 from "../../../docs/agent-artifacts/archive/README.md?collection=docs"
import * as __fd_glob_45 from "../../../docs/design/02-components.mdx?collection=docs"
import * as __fd_glob_44 from "../../../docs/design/01-styling-and-theming.mdx?collection=docs"
import * as __fd_glob_43 from "../../../docs/design/00-index.mdx?collection=docs"
import * as __fd_glob_42 from "../../../docs/roadmap/product.mdx?collection=docs"
import * as __fd_glob_41 from "../../../docs/roadmap/00-roadmap-index.mdx?collection=docs"
import * as __fd_glob_40 from "../../../docs/how-to/22-ai-generation-components.mdx?collection=docs"
import * as __fd_glob_39 from "../../../docs/how-to/21-migration-guide-workspace-to-editor.mdx?collection=docs"
import * as __fd_glob_38 from "../../../docs/how-to/20-create-a-workspace.mdx?collection=docs"
import * as __fd_glob_37 from "../../../docs/how-to/15-shadcn-registries-and-components.mdx?collection=docs"
import * as __fd_glob_36 from "../../../docs/how-to/14-marketing-announcements-scheduling.mdx?collection=docs"
import * as __fd_glob_35 from "../../../docs/how-to/13-marketing-email-newsletter.mdx?collection=docs"
import * as __fd_glob_34 from "../../../docs/how-to/12-marketing-stripe.mdx?collection=docs"
import * as __fd_glob_33 from "../../../docs/how-to/11-marketing-auth.mdx?collection=docs"
import * as __fd_glob_32 from "../../../docs/how-to/10-marketing-site.mdx?collection=docs"
import * as __fd_glob_31 from "../../../docs/how-to/09-twick-workspace.mdx?collection=docs"
import * as __fd_glob_30 from "../../../docs/how-to/08-adding-ai-to-workspaces.mdx?collection=docs"
import * as __fd_glob_29 from "../../../docs/how-to/07-copilot.mdx?collection=docs"
import * as __fd_glob_28 from "../../../docs/how-to/06-forge-workspace-walkthrough.mdx?collection=docs"
import * as __fd_glob_27 from "../../../docs/how-to/05-building-a-workspace.mdx?collection=docs"
import * as __fd_glob_26 from "../../../docs/how-to/04-data-and-state.mdx?collection=docs"
import * as __fd_glob_25 from "../../../docs/how-to/03-styling.mdx?collection=docs"
import * as __fd_glob_24 from "../../../docs/how-to/02-workspace-shell.mdx?collection=docs"
import * as __fd_glob_23 from "../../../docs/how-to/01-foundation.mdx?collection=docs"
import * as __fd_glob_22 from "../../../docs/how-to/00-index.mdx?collection=docs"
import * as __fd_glob_21 from "../../../docs/architecture/06-model-routing-and-openrouter.mdx?collection=docs"
import * as __fd_glob_20 from "../../../docs/architecture/05-editor-platform.mdx?collection=docs"
import * as __fd_glob_19 from "../../../docs/architecture/04-component-library-and-registry.mdx?collection=docs"
import * as __fd_glob_18 from "../../../docs/architecture/03-copilotkit-and-agents.mdx?collection=docs"
import * as __fd_glob_17 from "../../../docs/architecture/02-workspace-editor-architecture.mdx?collection=docs"
import * as __fd_glob_16 from "../../../docs/architecture/01-unified-workspace.mdx?collection=docs"
import * as __fd_glob_15 from "../../../docs/architecture/00-index.mdx?collection=docs"
import * as __fd_glob_14 from "../../../docs/tech-stack.md?collection=docs"
import * as __fd_glob_13 from "../../../docs/STATUS.md?collection=docs"
import * as __fd_glob_12 from "../../../docs/19-coding-agent-strategy.mdx?collection=docs"
import * as __fd_glob_11 from "../../../docs/18-agent-artifacts-index.mdx?collection=docs"
import * as __fd_glob_10 from "../../../docs/17-co-agents-and-multi-agent.mdx?collection=docs"
import * as __fd_glob_9 from "../../../docs/16-copilotkit-workspace-integration.mdx?collection=docs"
import * as __fd_glob_8 from "../../../docs/15-ai-workspace-integration.mdx?collection=docs"
import * as __fd_glob_7 from "../../../docs/14-adding-domain-actions.mdx?collection=docs"
import * as __fd_glob_6 from "../../../docs/13-code-organization.mdx?collection=docs"
import * as __fd_glob_5 from "../../../docs/12-workspace-design.mdx?collection=docs"
import * as __fd_glob_4 from "../../../docs/11-tech-stack.mdx?collection=docs"
import * as __fd_glob_3 from "../../../docs/10-project-overview.mdx?collection=docs"
import * as __fd_glob_2 from "../../../docs/00-docs-index.mdx?collection=docs"
import { default as __fd_glob_1 } from "../../../docs/how-to/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../../../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "../../docs", {"meta.json": __fd_glob_0, "how-to/meta.json": __fd_glob_1, }, {"00-docs-index.mdx": __fd_glob_2, "10-project-overview.mdx": __fd_glob_3, "11-tech-stack.mdx": __fd_glob_4, "12-workspace-design.mdx": __fd_glob_5, "13-code-organization.mdx": __fd_glob_6, "14-adding-domain-actions.mdx": __fd_glob_7, "15-ai-workspace-integration.mdx": __fd_glob_8, "16-copilotkit-workspace-integration.mdx": __fd_glob_9, "17-co-agents-and-multi-agent.mdx": __fd_glob_10, "18-agent-artifacts-index.mdx": __fd_glob_11, "19-coding-agent-strategy.mdx": __fd_glob_12, "STATUS.md": __fd_glob_13, "tech-stack.md": __fd_glob_14, "architecture/00-index.mdx": __fd_glob_15, "architecture/01-unified-workspace.mdx": __fd_glob_16, "architecture/02-workspace-editor-architecture.mdx": __fd_glob_17, "architecture/03-copilotkit-and-agents.mdx": __fd_glob_18, "architecture/04-component-library-and-registry.mdx": __fd_glob_19, "architecture/05-editor-platform.mdx": __fd_glob_20, "architecture/06-model-routing-and-openrouter.mdx": __fd_glob_21, "how-to/00-index.mdx": __fd_glob_22, "how-to/01-foundation.mdx": __fd_glob_23, "how-to/02-workspace-shell.mdx": __fd_glob_24, "how-to/03-styling.mdx": __fd_glob_25, "how-to/04-data-and-state.mdx": __fd_glob_26, "how-to/05-building-a-workspace.mdx": __fd_glob_27, "how-to/06-forge-workspace-walkthrough.mdx": __fd_glob_28, "how-to/07-copilot.mdx": __fd_glob_29, "how-to/08-adding-ai-to-workspaces.mdx": __fd_glob_30, "how-to/09-twick-workspace.mdx": __fd_glob_31, "how-to/10-marketing-site.mdx": __fd_glob_32, "how-to/11-marketing-auth.mdx": __fd_glob_33, "how-to/12-marketing-stripe.mdx": __fd_glob_34, "how-to/13-marketing-email-newsletter.mdx": __fd_glob_35, "how-to/14-marketing-announcements-scheduling.mdx": __fd_glob_36, "how-to/15-shadcn-registries-and-components.mdx": __fd_glob_37, "how-to/20-create-a-workspace.mdx": __fd_glob_38, "how-to/21-migration-guide-workspace-to-editor.mdx": __fd_glob_39, "how-to/22-ai-generation-components.mdx": __fd_glob_40, "roadmap/00-roadmap-index.mdx": __fd_glob_41, "roadmap/product.mdx": __fd_glob_42, "design/00-index.mdx": __fd_glob_43, "design/01-styling-and-theming.mdx": __fd_glob_44, "design/02-components.mdx": __fd_glob_45, "agent-artifacts/archive/README.md": __fd_glob_46, "agent-artifacts/core/compacting-and-archiving.md": __fd_glob_47, "agent-artifacts/core/debugging-zustand-devtools.md": __fd_glob_48, "agent-artifacts/core/decisions.md": __fd_glob_49, "agent-artifacts/core/errors-and-attempts.md": __fd_glob_50, "agent-artifacts/core/STATUS.md": __fd_glob_51, "agent-artifacts/core/tool-usage.md": __fd_glob_52, });