/**
 * Emit TypeScript for workspace layout in repo-studio or studio format.
 */

/**
 * @param {Array<{ workspaceId: string, label: string, panels: Array<{ id: string, title: string, rail: string }> }>} layouts
 * @param {'repo-studio'|'studio'} format
 * @param {object} options
 * @param {string} [options.panelKeyPrefix] - e.g. 'panel.visible.repo' -> key = prefix + '-' + id
 * @param {string} [options.panelKeyFormat] - e.g. 'panel.visible.{workspaceId}-{panelId}' for studio
 * @param {string} [options.workspaceIdsImport] - repo-studio: import path for REPO_WORKSPACE_IDS
 * @param {string} [options.fallbackWorkspaceId] - repo-studio: fallback workspace id
 * @param {string} [options.layoutIdPrefix] - repo-studio: e.g. 'repo'
 */
export function emitLayout(layouts, format, options = {}) {
  if (format === 'repo-studio') {
    return emitRepoStudioFormat(layouts, options);
  }
  if (format === 'studio') {
    return emitStudioFormat(layouts, options);
  }
  throw new Error(`Unknown layout format: ${format}`);
}

function panelKey(panelId, workspaceId, options) {
  if (options.panelKeyPrefix) {
    return `${options.panelKeyPrefix}-${panelId}`;
  }
  if (options.panelKeyFormat) {
    return options.panelKeyFormat.replace('{workspaceId}', workspaceId).replace('{panelId}', panelId);
  }
  return `panel.visible.${workspaceId}-${panelId}`;
}

function emitRepoStudioFormat(layouts, options) {
  const workspaceIds = layouts.map((l) => l.workspaceId);
  const allPanelIds = [...new Set(layouts.flatMap((l) => l.panels.map((p) => p.id)))].sort((a, b) =>
    a.localeCompare(b),
  );
  const workspaceLabels = Object.fromEntries(layouts.map((l) => [l.workspaceId, l.label]));
  const layoutDefinitions = {};
  const prefix = options.panelKeyPrefix ?? 'panel.visible.repo';
  const layoutIdPrefix = options.layoutIdPrefix ?? 'repo';
  const fallbackWorkspaceId = options.fallbackWorkspaceId ?? workspaceIds[0];

  for (const layout of layouts) {
    const mainPanels = layout.panels.filter((p) => p.rail === 'main');
    const mainAnchorPanelId = mainPanels[0]?.id ?? layout.panels[0]?.id ?? '';
    const mainPanelIds = mainPanels.map((p) => p.id);
    const panelSpecs = layout.panels.map((p) => ({
      id: p.id,
      rail: p.rail,
      label: p.title,
      key: `${prefix}-${p.id}`,
    }));
    layoutDefinitions[layout.workspaceId] = {
      workspaceId: layout.workspaceId,
      label: layout.label,
      layoutId: `${layoutIdPrefix}-${layout.workspaceId}`,
      mainAnchorPanelId,
      mainPanelIds,
      panelSpecs,
    };
  }

  const workspaceIdsImport = options.workspaceIdsImport ?? "@/lib/types";

  return `/**
 * Do not edit. Generated by @forge/forge-codegen.
 * Source: workspace components (WORKSPACE_ID, WORKSPACE_LABEL, WorkspaceLayout.Panel).
 */

import { REPO_WORKSPACE_IDS, type RepoWorkspaceId } from '${workspaceIdsImport}';

export type RepoPanelRail = 'left' | 'main' | 'right' | 'bottom';

export const REPO_PANEL_IDS = ${JSON.stringify(allPanelIds)} as const;

export type RepoPanelId = (typeof REPO_PANEL_IDS)[number];

export type RepoWorkspacePanelSpec = {
  id: RepoPanelId;
  label: string;
  key: string;
  rail: RepoPanelRail;
};

export type RepoWorkspaceLayoutDefinition = {
  workspaceId: RepoWorkspaceId;
  label: string;
  layoutId: string;
  mainAnchorPanelId: RepoPanelId;
  mainPanelIds: RepoPanelId[];
  panelSpecs: RepoWorkspacePanelSpec[];
};

export const REPO_WORKSPACE_LABELS: Record<RepoWorkspaceId, string> = ${JSON.stringify(workspaceLabels, null, 2)};

const LAYOUT_DEFINITIONS: Record<RepoWorkspaceId, RepoWorkspaceLayoutDefinition> = ${JSON.stringify(layoutDefinitions, null, 2)};

const FALLBACK_WORKSPACE_ID: RepoWorkspaceId = ${JSON.stringify(fallbackWorkspaceId)};

function getDefinitionSafe(workspaceId: string): RepoWorkspaceLayoutDefinition {
  if (workspaceId in LAYOUT_DEFINITIONS) {
    return LAYOUT_DEFINITIONS[workspaceId as RepoWorkspaceId];
  }
  if (process.env.NODE_ENV !== 'production') {
    console.warn(
      '[Repo Studio] Unknown workspace id "%s", falling back to planning.',
      workspaceId,
    );
  }
  return LAYOUT_DEFINITIONS[FALLBACK_WORKSPACE_ID];
}

export function getWorkspaceLayoutDefinition(workspaceId: RepoWorkspaceId): RepoWorkspaceLayoutDefinition {
  return LAYOUT_DEFINITIONS[workspaceId];
}

export function getWorkspaceLayoutId(workspaceId: string): string {
  return getDefinitionSafe(workspaceId).layoutId;
}

export function getWorkspacePanelSpecs(workspaceId: string): RepoWorkspacePanelSpec[] {
  return getDefinitionSafe(workspaceId).panelSpecs;
}

function normalizePanelIds(panelIds: unknown[]) {
  return [...new Set(
    (panelIds || [])
      .map((panelId) => String(panelId || '').trim())
      .filter(Boolean),
  )];
}

export function sanitizeWorkspaceHiddenPanelIds(
  workspaceId: RepoWorkspaceId,
  panelIds: unknown[],
): string[] {
  const definition = getWorkspaceLayoutDefinition(workspaceId);
  const allowedIds = new Set<string>(definition.panelSpecs.map((panel) => panel.id));
  const hidden = normalizePanelIds(panelIds)
    .filter((panelId) => allowedIds.has(panelId));
  const hiddenSet = new Set(hidden);
  const visibleMainPanels = definition.mainPanelIds.filter((panelId) => !hiddenSet.has(panelId));
  if (visibleMainPanels.length === 0) {
    hiddenSet.delete(definition.mainAnchorPanelId);
    const fallbackVisibleMainPanels = definition.mainPanelIds.filter((panelId) => !hiddenSet.has(panelId));
    if (fallbackVisibleMainPanels.length === 0 && definition.mainPanelIds[0]) {
      hiddenSet.delete(definition.mainPanelIds[0]);
    }
  }
  return [...hiddenSet].sort((a, b) => a.localeCompare(b));
}

export function createEmptyWorkspaceHiddenPanelMap(): Partial<Record<RepoWorkspaceId, string[]>> {
  return REPO_WORKSPACE_IDS.reduce((acc, workspaceId) => {
    acc[workspaceId] = [];
    return acc;
  }, {} as Partial<Record<RepoWorkspaceId, string[]>>);
}
`;
}

function emitStudioFormat(layouts, options) {
  const keyFormat = options.panelKeyFormat ?? 'panel.visible.{workspaceId}-{panelId}';
  const extraPanels = options.extraPanels ?? {};
  const specs = {};
  for (const layout of layouts) {
    const base = layout.panels.map((p) => ({
      id: p.id,
      label: p.title,
      key: keyFormat.replace('{workspaceId}', layout.workspaceId).replace('{panelId}', p.id),
    }));
    const extra = extraPanels[layout.workspaceId] ?? [];
    specs[layout.workspaceId] = [...base, ...extra];
  }
  for (const workspaceId of Object.keys(extraPanels)) {
    if (!specs[workspaceId]) specs[workspaceId] = extraPanels[workspaceId];
  }
  return `/**
 * Do not edit. Generated by @forge/forge-codegen.
 * Source: workspace components (WORKSPACE_ID, WORKSPACE_LABEL, WorkspaceLayout.Panel).
 */

export interface WorkspacePanelSpec {
  id: string;
  label: string;
  key: string;
}

export const WORKSPACE_PANEL_SPECS: Record<string, WorkspacePanelSpec[]> = ${JSON.stringify(specs, null, 2)};
`;
}
