/**
 * Settings codegen: load registry module (buildDefaultsFromRegistry), optionally merge with app defaults, write TS file.
 * No React; registry module must be importable without mounting React.
 */

import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export function deepMerge(target, source) {
  const out = { ...target };
  for (const key of Object.keys(source)) {
    if (
      source[key] != null &&
      typeof source[key] === 'object' &&
      !Array.isArray(source[key]) &&
      target[key] != null &&
      typeof target[key] === 'object' &&
      !Array.isArray(target[key])
    ) {
      out[key] = deepMerge(out[key] || {}, source[key]);
    } else if (source[key] !== undefined) {
      out[key] = source[key];
    }
  }
  return out;
}

/**
 * Load registry and call buildDefaultsFromRegistry (or buildRepoSettingsDefaultsFromRegistry).
 * @param {string} registryPath - absolute or relative path to registry module
 * @param {string} cwd - base for resolving relative path
 * @returns {Promise<Record<string, unknown>>}
 */
export async function loadRegistryDefaults(registryPath, cwd) {
  const resolved = path.isAbsolute(registryPath) ? registryPath : path.join(cwd, registryPath);
  const url = pathToFileURL(resolved).href;
  const registry = await import(url);
  const fn =
    registry.buildDefaultsFromRegistry ??
    registry.buildRepoSettingsDefaultsFromRegistry ??
    registry.buildAppSettingsDefaultsFromRegistry;
  if (typeof fn !== 'function') {
    throw new Error(
      `Registry at ${resolved} must export buildDefaultsFromRegistry, buildRepoSettingsDefaultsFromRegistry, or buildAppSettingsDefaultsFromRegistry`,
    );
  }
  return fn();
}

/**
 * Generate and return the TypeScript source for a defaults file.
 * @param {Record<string, unknown>} defaults - merged defaults object
 * @param {string} exportName - e.g. 'REPO_SETTINGS_GENERATED_DEFAULTS' or 'APP_DEFAULTS'
 * @param {string} [header] - optional extra comment lines
 */
export function emitSettingsDefaultsTs(defaults, exportName, header = '') {
  const comment =
    `/**\n * Do not edit. Generated by @forge/forge-codegen.\n` +
    (header ? ` * ${header}\n` : '') +
    ` */\n\n`;
  return `${comment}export const ${exportName} = ${JSON.stringify(defaults, null, 2)} as const;\n`;
}
