/**
 * Do not edit. Generated by @forge/forge-codegen.
 * Source: workspace components (WORKSPACE_ID, WORKSPACE_LABEL, WorkspaceLayout.Panel).
 * Single import surface for this studio app.
 */

import type { WorkspacePanelSpec, WorkspaceLayoutDefinition } from '@forge/shared';

export const WORKSPACE_IDS = ["assistant"] as const;
export type WorkspaceId = (typeof WORKSPACE_IDS)[number];

export const WORKSPACE_LABELS: Record<WorkspaceId, string> = {
  "assistant": "AI Chat"
};

/** Panel ids that must never be hidden (e.g. viewport-as-canvas). */
export const PINNED_PANEL_IDS: readonly string[] = [];

const LAYOUT_DEFINITIONS: Record<WorkspaceId, WorkspaceLayoutDefinition> = {
  "assistant": {
    "workspaceId": "assistant",
    "label": "AI Chat",
    "layoutId": "consumer-studio-assistant",
    "mainAnchorPanelId": "assistant-chat",
    "mainPanelIds": [
      "assistant-chat"
    ],
    "panelSpecs": [
      {
        "id": "assistant-chat",
        "rail": "main",
        "label": "Assistant",
        "key": "panel.visible.assistant-assistant-chat"
      }
    ]
  }
};

const FALLBACK_WORKSPACE_ID: WorkspaceId = "assistant";

function getDefinitionSafe(workspaceId: string): WorkspaceLayoutDefinition {
  if (workspaceId in LAYOUT_DEFINITIONS) {
    return LAYOUT_DEFINITIONS[workspaceId as WorkspaceId];
  }
  if (process.env.NODE_ENV !== 'production') {
    console.warn(
      '[App spec] Unknown workspace id "%s", falling back to %s.',
      workspaceId,
      FALLBACK_WORKSPACE_ID,
    );
  }
  return LAYOUT_DEFINITIONS[FALLBACK_WORKSPACE_ID];
}

export function getWorkspaceLayoutDefinition(workspaceId: WorkspaceId): WorkspaceLayoutDefinition {
  return LAYOUT_DEFINITIONS[workspaceId];
}

export function getWorkspaceLayoutId(workspaceId: string): string {
  return getDefinitionSafe(workspaceId).layoutId;
}

export function getWorkspacePanelSpecs(workspaceId: string): WorkspacePanelSpec[] {
  return getDefinitionSafe(workspaceId).panelSpecs;
}

function normalizePanelIds(panelIds: unknown[]) {
  return [...new Set(
    (panelIds || [])
      .map((panelId) => String(panelId || '').trim())
      .filter(Boolean),
  )];
}

export function sanitizeWorkspaceHiddenPanelIds(workspaceId: WorkspaceId, panelIds: unknown[]): string[] {
  const definition = getWorkspaceLayoutDefinition(workspaceId);
  const allowedIds = new Set(definition.panelSpecs.map((p) => p.id));
  const pinnedSet = new Set(PINNED_PANEL_IDS);
  const hidden = normalizePanelIds(panelIds)
    .filter((id) => allowedIds.has(id))
    .filter((id) => !pinnedSet.has(id));
  const hiddenSet = new Set(hidden);
  const visibleMainPanels = definition.mainPanelIds.filter((id) => !hiddenSet.has(id));
  if (visibleMainPanels.length === 0) {
    hiddenSet.delete(definition.mainAnchorPanelId);
    const fallbackVisible = definition.mainPanelIds.filter((id) => !hiddenSet.has(id));
    if (fallbackVisible.length === 0 && definition.mainPanelIds[0]) {
      hiddenSet.delete(definition.mainPanelIds[0]);
    }
  }
  return [...hiddenSet].sort((a, b) => a.localeCompare(b));
}

export function createEmptyWorkspaceHiddenPanelMap(): Partial<Record<WorkspaceId, string[]>> {
  return WORKSPACE_IDS.reduce((acc, workspaceId) => {
    acc[workspaceId] = [];
    return acc;
  }, {} as Partial<Record<WorkspaceId, string[]>>);
}

/** Merged settings defaults for this app. */
export const APP_SETTINGS_DEFAULTS = {} as const;
