// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"changelog.md": () => import("../content/docs/changelog.md?collection=docs"), "features.md": () => import("../content/docs/features.md?collection=docs"), "getting-started.md": () => import("../content/docs/getting-started.md?collection=docs"), "index.md": () => import("../content/docs/index.md?collection=docs"), "pricing.md": () => import("../content/docs/pricing.md?collection=docs"), "roadmap.md": () => import("../content/docs/roadmap.md?collection=docs"), "ai/assistant-chat.md": () => import("../content/docs/ai/assistant-chat.md?collection=docs"), "ai/copilot.md": () => import("../content/docs/ai/copilot.md?collection=docs"), "ai/domain-actions.md": () => import("../content/docs/ai/domain-actions.md?collection=docs"), "ai/index.md": () => import("../content/docs/ai/index.md?collection=docs"), "ai/openrouter.md": () => import("../content/docs/ai/openrouter.md?collection=docs"), "api-reference/agent-engine.md": () => import("../content/docs/api-reference/agent-engine.md?collection=docs"), "api-reference/dev-kit.md": () => import("../content/docs/api-reference/dev-kit.md?collection=docs"), "api-reference/index.md": () => import("../content/docs/api-reference/index.md?collection=docs"), "api-reference/types.md": () => import("../content/docs/api-reference/types.md?collection=docs"), "components/dock-layout.md": () => import("../content/docs/components/dock-layout.md?collection=docs"), "components/editor-shell.md": () => import("../content/docs/components/editor-shell.md?collection=docs"), "components/index.md": () => import("../content/docs/components/index.md?collection=docs"), "components/panel-tabs.md": () => import("../content/docs/components/panel-tabs.md?collection=docs"), "editors/character.md": () => import("../content/docs/editors/character.md?collection=docs"), "editors/dialogue.md": () => import("../content/docs/editors/dialogue.md?collection=docs"), "editors/index.md": () => import("../content/docs/editors/index.md?collection=docs"), "editors/strategy.md": () => import("../content/docs/editors/strategy.md?collection=docs"), "editors/video.md": () => import("../content/docs/editors/video.md?collection=docs"), "yarn-spinner/export.md": () => import("../content/docs/yarn-spinner/export.md?collection=docs"), "yarn-spinner/import.md": () => import("../content/docs/yarn-spinner/import.md?collection=docs"), "yarn-spinner/index.md": () => import("../content/docs/yarn-spinner/index.md?collection=docs"), "yarn-spinner/node-types.md": () => import("../content/docs/yarn-spinner/node-types.md?collection=docs"), "yarn-spinner/syntax-reference.md": () => import("../content/docs/yarn-spinner/syntax-reference.md?collection=docs"), }),
};
export default browserCollections;